M48
; DRILL file {KiCad 8.0.0-8.0.0-1~ubuntu22.04.1} date 2024-03-06T20:03:26+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-06T20:03:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-8.0.0-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0906
%
G90
G05
T1
X5.628Y-1.1244
X6.1004Y-1.1244
M30
